### ISSUE TITLE
Clipping issues at high frames size

### ISSUE THREAD

**Issue by SlashScreen** [zhangjt93/godot-imposter#1]
Wonderful work here, really a lifesaver.
However, I noticed that at a high frame count, the generated cube begins to clip into the camera, as seen here: 
![image](https://github.com/zhangjt93/godot-imposter/assets/12375239/e1f5094b-8e18-4047-a894-59432783a0f9)

**Comment by zhangjt93** [comment]
> Wonderful work here, really a lifesaver. However, I noticed that at a high frame count, the generated cube begins to clip into the camera, as seen here: ![image](https://user-images.githubusercontent.com/12375239/279612795-e1f5094b-8e18-4047-a894-59432783a0f9.png)

Thank you for your feedback. I will attempt to fix this issue. Please stay tuned for further updates.

**Comment by zhangjt93** [comment]
Thank you once again for your feedback.  This issue is related to the camera's near clipping plane.  I have already set a value for it, and it seems to have resolved your issue.  As for the appropriate value for this parameter, I will continue monitoring and testing.  Thank you for your support.

SHA：09feee2369d065e7616107b5fc9b8dd97d7de0ba
